name: untitled3
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^4.0.3
  intl: ^0.18.0 # Agrega esta línea para intl
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.0


 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Medium.ttf


